   [package]
   name = "CertificateVerifierDApp"
   version = "0.0.1"

   [addresses]
   certificate_addr = "0x508c171f342571cbae2061ce37ea68a74db941a8fc62cd03c9bd26cc15a5b017"

   [dependencies]
   AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }